version: '3.1'
services:
  mongo-container:
    image: mongo:latest
    container_name: mongo-server
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongo:/data/db"
      - "/data/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod